name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-ubuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: make
      run: cd src && make && rm *.o

  build-win:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: make
      run: cd src && clang++ *.cpp -O3 -pipe -march=native -Wall -flto -DNDEBUG -mpopcnt -m64 -mbmi2 -std=c++23 -o cc0.exe
