name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-ubuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make src
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck

  build-win:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make src
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
