name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-ubuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: make
      run: cd src && make && rm *.o

  build-win:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: make
    - shell: bash
      run: cd src && make
